main_app/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('albums/', views.albums_index, name='index'),
    path('albums/<int:album_id>/', views.albums_detail, name='detail'),
    path('albums/create/', views.AlbumCreate.as_view(), name='albums_create'),
    path('albums/<int:pk>/update/', views.AlbumUpdate.as_view(), name='albums_update'),
    path('albums/<int:pk>/delete/', views.AlbumDelete.as_view(), name='albums_delete'),
    path('albums/<int:album_id>/add_review/', views.add_review, name='add_review'),
    path('albums/<int:album_id>/add_photo', views.add_photo, name='add_photo'),
    path('formats/', views.FormatList.as_view(), name='formats_index'),
    path('formats/<int:pk>/', views.FormatDetail.as_view(), name='formats_detail'),
    path('formats/create/', views.FormatCreate.as_view(), name='formats_create'),
    path('formats/<int:pk>/update/', views.FormatUpdate.as_view(), name='formats_update'),
    path('formats/<int:pk>/delete/', views.FormatDelete.as_view(), name='formats_delete'),
    path('albums/<int:album_id>/assoc_format/<int:format_id>/', views.assoc_format, name='assoc_format')
]

sourcereview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date


REVIEWS =(
    ('C', 'Classic'),
    ('O', 'Okay '),
    ('B', 'Bad')
)

class Format(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('formats_detail', kwargs={'pk': self.id})


class Album(models.Model):
    name = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    article = models.TextField(max_length=10000, default="")
    year = models.IntegerField()
    formats = models.ManyToManyField(Format)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'album_id': self.id})
    
class Review(models.Model):
    date = models.DateField('Reading Date')
    piece = models.CharField(
        max_length=1,
            choices=REVIEWS,
            default=REVIEWS[0][0]
        )
    
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_piece_display()} on {self.date}'
    
    class Meta:
        ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for album_id: {self.album_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['date', 'piece']

main_app/views.py
from django.shortcuts import render, redirect
import os
import boto3
import uuid
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Album, Format, Photo
from .forms import ReviewForm



# Create your views here.

def home(request):
    return render (request, 'home.html')

def about(request):
    return render(request, 'about.html')

def albums_index(request):
    albums = Album.objects.all()
    return render(request, 'albums/index.html', { 'albums': albums })

def albums_detail(request, album_id):
    album = Album.objects.get(id=album_id)
    id_list = album.formats.all().values_list('id')
    formats_album_doesnt_have = Format.objects.exclude(id__in=id_list)
    review_form = ReviewForm()
    return render(request, 'albums/detail.html', {
       'album':album, 
       'review_form' : review_form,
       'formats': formats_album_doesnt_have})

def add_review(request, album_id):
    form = ReviewForm(request.POST)
    if form.is_valid():
        new_review = form.save(commit=False)
        new_review.album_id = album_id
        new_review.save()
    return redirect('detail', album_id=album_id)

def assoc_format(request, album_id, format_id):
   Album.objects.get(id=album_id).formats.add(format_id)
   return redirect('detail', album_id=album_id)

class AlbumCreate(CreateView):
    model =  Album
    fields = ['name','artist','company', 'article', 'year']
    # success_url = '/albums/'

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['name','artist','article']

class AlbumDelete(DeleteView):
    model = Album
    success_url = '/albums/'

class FormatList(ListView):
  model = Format

class FormatDetail(DetailView):
  model = Format

class FormatCreate(CreateView):
  model = Format
  fields = '__all__'

class FormatUpdate(UpdateView):
  model = Format
  fields = ['name']

class FormatDelete(DeleteView):
  model = Format
  success_url = '/formats/'

def some_function(request):
   secret_key = os.environ['SECRET_KEY']

def add_photo(request, album_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            # build the full url string
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            Photo.objects.create(url=url, album_id=album_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', album_id=album_id)

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>Album Reviews</h1>
<hr />
<p>Hire Album Reviewer</p>

{% endblock %}

main_app/templates/albums/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Album Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ album.name }}</span>
        <p>Artist: {{ album.artist }}</p>
        <p>Company: {{ album.company }}</p>
        <p>Year Released: {{ album.year }}</p>
        <p>Article: {{ album.article|linebreaks }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'albums_update' album.id %}">Edit</a>
        <a href="{% url 'albums_delete' album.id %}">Delete</a>
      </div>
    </div>
  </div>

  <div class="col s6">
    {% for photo in album.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}" />
    {% empty %}
    <div class="card-panel red-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form
      action="{% url 'add_photo' album.id %}"
      enctype="multipart/form-data"
      method="POST"
      class="card-panel"
    >
      {% csrf_token %}
      <input type="file" name="photo-file" />
      <br /><br />
      <input type="submit" class="btn" value="Upload Photo" />
    </form>
  </div>

  <div class="row1">
    <div class="col s6">
      <h3>Article Review</h3>
      <form action="{% url 'add_review' album.id %}" method="POST">
        {% csrf_token %} {{ review_form.as_p }}
        <input type="submit" class="btn" value="Add Review" />
      </form>
      <table class="striped">
        <thead>
          <tr>
            <th>Date</th>
            <th>Review</th>
          </tr>
        </thead>
        <tbody>
          {% for review in album.review_set.all %}
          <tr>
            <td>{{review.date}}</td>
            <td>{{review.get_piece_display}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <div class="row3">
    <div class="col s6">
      <h3>{{ album.name }} Formats</h3>
      {% if album.formats.count %} {% for format in album.formats.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title"> {{ format.name }} </span>
        </div>
      </div>
      {% endfor %} {% else %}
      <h5>No Format :(</h5>
      {% endif %}
    </div>
    <div class="row2">
      <div class="col s6">
        {% if formats.count %} {% for format in formats.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title"> {{ format.name }} </span>
          </div>
          <div class="card-action">
            <form
              action="{% url 'assoc_format' album.id format.id %}"
              method="POST"
            >
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
          {% endfor %} {% else %} {% endif %}
        </div>
      </div>
    </div>
  </div>

  <script>
    const dateEl = document.getElementById("id_date");
    M.Datepicker.init(dateEl, {
      format: "yyyy-mm-dd",
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true,
    });

    const selectEl = document.getElementById("id_piece");
    M.FormSelect.init(selectEl);
  </script>

  {% endblock %}
</div>

main_app/templates/albums/index.html
{% extends 'base.html' %} {% block content %}

<h1>Album List</h1>

{% for album in albums %}
  <div class="card">
    <a href="{% url 'detail' album.id %}">
            <div class="card horizontal">
              <div class="card-content">
                {% for photo in album.photo_set.all %}
                <img class="responsive-img card-panel" src="{{photo.url}}" />
                {% endfor %}
              </div>
          <div class="card-content">
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <span class="card-title">{{ album.name }}</span>
        </a>
            <p>Artist: {{ album.artist }}</p>
            <p>Record Company: {{ album.company }}</p>
            <p>Year Released: {{ album.year }}</p>
          </div>
        </div>
  </div>

{% endfor %} {% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Source Album Review</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="{% url 'home' %}" class="left brand-logo"
                >&nbsp;&nbsp;Album Reviews</a
              >
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <!-- <li><a href="{% url 'formats_create' %}">Add a Format</a></li> -->
             <li><a href="{% url 'formats_index' %}">View All Formats</a></li>
            <li><a href="{% url 'albums_create' %}">Add an Album</a></li>
            <li><a href="{% url 'index' %}">View All the Albums</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
        All Rights Reserved, &copy; 2023 Album Review &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/album_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Album</h1>

<h4>
  Are you sure you want to delete
  <span class="red-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' album.id %}" class="btn">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/album_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="red-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Album</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Add Album!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/format_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Format</h1>

<h4>
  Are you sure you want to delete
  <span class="red-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'formats_detail' object.id %}" class="btn">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/format_detail.html
{% extends 'base.html' %} {% block content %}

<h1>Format Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ format.name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'formats_update' format.id %}">Edit</a>
        <a href="{% url 'formats_delete' format.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/format_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="red-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Format</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/format_list.html
{% extends 'base.html' %} {% block content %}

<h1>Format List</h1>

{% for format in format_list %}
<a href="{% url 'formats_detail' format.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ format.name }}</span>
    </div>
  </div>
</a>
{% endfor %} {% endblock %}